# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
vacation_df = pd.read_csv("C:\\Users\\goooo\\Git\\python-api-challenge\\vacationdata.csv")
vacation_df.head()

,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed (mph)
0,Torbay,47.6666,-52.7314,19.670,73,90,11.32
1,Carnarvon,-24.8667,113.6333,80.600,65,0,9.26
2,Ushuaia,-54.8000,-68.3000,64.400,48,40,6.69
3,Daman,20.4167,72.8500,79.970,28,100,2.41
4,Tignère,7.3667,12.6500,60.008,28,75,0.62

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key) 
locations = vacation_df[["Latitude", "Longitude"]].astype(float)
humidity = vacation_df["Humidity"].astype(float)

In [4]:
 # Create a Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
eighty_df = vacation_df.loc[(vacation_df['Temperature'] < 80)]
temp_df = eighty_df.loc[(eighty_df['Temperature'] > 70)]
wind_df = temp_df.loc[(temp_df['Wind Speed (mph)'] < 10)]
narrow_df = wind_df.loc[(wind_df['Cloudiness'] == 0)]

narrow_df

,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed (mph)
7,Hobart,-42.8794,147.3294,74.066,40,0,5.14
71,Cockburn Town,21.4612,-71.1419,76.676,76,0,8.07
81,East London,-33.0153,27.9116,71.600,94,0,3.09
138,Lima,-12.0432,-77.0282,75.074,69,0,2.57
170,Puerto Escondido,15.8500,-97.0667,76.388,73,0,2.87
234,Christchurch,-43.5333,172.6333,75.794,25,0,3.60
242,Flinders,-34.5833,150.8552,79.430,59,0,1.79
258,San Ignacio,17.1561,-89.0714,72.266,78,0,3.09
297,Salalah,17.0151,54.0924,75.200,41,0,6.17
307,Bhilwara,25.3500,74.6333,75.812,19,0,2.25
353,Faizabad,26.7833,82.1333,72.536,44,0,2.08
372,Tura,25.5198,90.2201,78.584,28,0,1.52
416,Chilca,-12.5211,-76.7372,74.516,69,0,2.57
426,Iralaya,15.0000,-83.2333,75.992,85,0,3.42
427,Iquique,-20.2208,-70.1431,71.600,56,0,2.57
461,Pisco,-13.7000,-76.2167,71.348,78,0,2.57
474,Umluj,25.0213,37.2685,76.550,40,0,4.93
496,Sittwe,20.1500,92.9000,79.466,32,0,2.00
503,Mandurah,-32.5500,115.7000,76.046,35,0,4.63
506,Sakon Nakhon,17.1612,104.1472,73.400,53,0,2.06

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = narrow_df.copy()
hotel_df["Hotel Name"] = ""
radius = 5000
seattle_coords = "47.6062095,-122.3320708"

params = {
    "location": seattle_coords,
    "types": "hotel",
    "radius": radius,
    "key": g_key
}

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
response = requests.get(base_url, params)
seattle_bikes = response.json()

In [7]:
print(seattle_bikes)

{'error_message': 'You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started', 'html_attributions': [], 'results': [], 'status': 'REQUEST_DENIED'}

In [41]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

KeyError: 'Country'

In [8]:
# Add marker layer ontop of heat map


# Display figure
print("The heat map couldn't be completed because the API key for Places is denied. Google Cloud Platform errors out whenever I try to download the Places api key.")

The heat map couldn't be completed because the API key for Places is denied. Google Cloud Platform errors out whenever I try to download the Places api key.